version: '3.9'

services:

  sample-db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - db-local
    ports:
      - 5432:5432

networks:
  db-local: